# Generated by Django 4.0 on 2022-05-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stress_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('step_count', models.IntegerField()),
                ('stress_level', models.CharField(max_length=100)),
            ],
        ),
    ]
